#!/usr/bin/env bash
# Read/modify/write config/species.sh.
#
# On disk each entry is a single string: "key|fna_url|gtf_url|active",
# optionally split over several lines with backslash continuations. In memory
# the table is held as four parallel arrays so entries can be edited by index:
#   SP_KEYS  SP_FNA  SP_GTF  SP_ACTIVE

# Split one "key|fna|gtf|active" entry into the caller's four named variables,
# stripping the whitespace and backslashes introduced by line continuations.
species_entry_split() {
    local __entry="$1"
    local __out_vars=( "$2" "$3" "$4" "$5" )
    local __fields __i __value
    IFS='|' read -r -a __fields <<< "$__entry"

    for __i in 0 1 2 3; do
        __value="${__fields[$__i]:-}"
        __value="${__value//[$'\t\r\n\\']/}"
        __value="${__value#"${__value%%[![:space:]]*}"}"   # ltrim
        __value="${__value%"${__value##*[![:space:]]}"}"   # rtrim
        printf -v "${__out_vars[$__i]}" '%s' "$__value"
    done
    # An entry without an explicit flag is active.
    [[ -z "${!5}" ]] && printf -v "$5" '%s' "true"
    return 0
}

# Print the keys of every entry marked active in the current SPECIES_CONFIG.
species_config_active_keys() {
    local entry key fna gtf active
    for entry in "${SPECIES_CONFIG[@]}"; do
        species_entry_split "$entry" key fna gtf active
        [[ -n "$key" && "${active,,}" == "true" ]] && echo "$key"
    done
    return 0
}

# Load a species config file into the SP_* arrays.
species_config_load() {
    local file="$1"
    SP_KEYS=(); SP_FNA=(); SP_GTF=(); SP_ACTIVE=()

    [[ -f "$file" ]] || return 0
    # shellcheck disable=SC1090
    source "$file"

    local entry key fna gtf active
    for entry in "${SPECIES_CONFIG[@]}"; do
        species_entry_split "$entry" key fna gtf active
        [[ -z "$key" ]] && continue
        SP_KEYS+=( "$key" ); SP_FNA+=( "$fna" )
        SP_GTF+=( "$gtf" );  SP_ACTIVE+=( "$active" )
    done
}

# Echo the index of a species key in SP_KEYS, or -1 when absent.
species_config_index() {
    local key="$1" i
    for i in "${!SP_KEYS[@]}"; do
        [[ "${SP_KEYS[$i]}" == "$key" ]] && { echo "$i"; return 0; }
    done
    echo "-1"
}

# Insert or replace one entry. Sets SPECIES_CONFIG_LAST_ACTION to "added" or
# "updated" — the caller must not run this in a subshell, or the arrays it
# mutates are discarded.
SPECIES_CONFIG_LAST_ACTION=""

species_config_upsert() {
    local key="$1" fna="$2" gtf="$3" active="${4:-true}"
    local idx; idx="$(species_config_index "$key")"

    if (( idx >= 0 )); then
        SP_FNA[$idx]="$fna"; SP_GTF[$idx]="$gtf"; SP_ACTIVE[$idx]="$active"
        SPECIES_CONFIG_LAST_ACTION="updated"
    else
        SP_KEYS+=( "$key" ); SP_FNA+=( "$fna" )
        SP_GTF+=( "$gtf" );  SP_ACTIVE+=( "$active" )
        SPECIES_CONFIG_LAST_ACTION="added"
    fi
}

# Write the SP_* arrays back out as a sourceable bash file.
species_config_save() {
    local file="$1" i
    local tmp="${file}.tmp"

    {
        echo '#!/usr/bin/env bash'
        echo '# Species reference table — generated by setup.sh.'
        echo '# Format per entry: "species_key|genome_fna_gz_url|genome_gtf_gz_url|active"'
        echo '# Set active=false to skip a species without removing the entry.'
        echo ''
        echo 'declare -a SPECIES_CONFIG=('
        for i in "${!SP_KEYS[@]}"; do
            echo ''
            printf '    "%s|\\\n' "${SP_KEYS[$i]}"
            printf '%s|\\\n'      "${SP_FNA[$i]}"
            printf '%s|\\\n'      "${SP_GTF[$i]}"
            printf '%s"\n'        "${SP_ACTIVE[$i]}"
        done
        echo ')'
    } > "$tmp" || { rm -f "$tmp"; return 1; }

    mv "$tmp" "$file"
}
